name: Render and Deploy Bookdown

on:
  push:
    branches: [ main ]

permissions:
  contents: write  # Required for GitHub Pages deployment

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      R_LIBS_USER: ${{ runner.workspaces }}/R/${{ github.run_id }}  # isolated cache per run

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('.github/workflows/bookdown.yaml') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install system dependencies
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install CRAN & Bioconductor packages if missing or outdated
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          Rscript --vanilla -e '
          # --- CRAN packages ---
          cran_pkgs <- c("remotes","bookdown")
          available_cran <- available.packages(repos="https://cloud.r-project.org")
          for (pkg in cran_pkgs) {
            installed <- tryCatch(packageVersion(pkg), error=function(e) NA)
            available <- available_cran[pkg, "Version"]
            if (is.na(installed) || installed < available) {
              install.packages(pkg, repos="https://cloud.r-project.org")
            }
          }

          # --- Bioconductor packages ---
          if (!requireNamespace("BiocManager", quietly=TRUE)) install.packages("BiocManager", repos="https://cloud.r-project.org")
          bioc_pkgs <- c("sparseMatrixStats")
          for (pkg in bioc_pkgs) {
            installed <- tryCatch(packageVersion(pkg), error=function(e) NA)
            available <- BiocManager::available(pkg)[pkg]
            if (is.na(installed) || installed < available) {
              BiocManager::install(pkg, ask=FALSE, update=FALSE)
            }
          }

          # --- Always install GitHub package modelSelection ---
          remotes::install_github("davidrusi/modelSelection", dependencies=TRUE, upgrade="never", auth_token=Sys.getenv("GITHUB_TOKEN"))
          '

      - name: Build site (HTML only)
        run: Rscript --vanilla -e 'bookdown::render_book("index.Rmd", output_format="bookdown::gitbook")'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          publish_branch: gh-pages
