name: Render and Deploy Bookdown

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('.github/workflows/bookdown.yaml') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Install system dependencies
        run: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages and dependencies
        run: |
          Rscript --vanilla -e 'install.packages("remotes", repos="https://cloud.r-project.org")'
          Rscript --vanilla -e 'install.packages("bookdown", repos="https://cloud.r-project.org")'
          Rscript --vanilla -e 'if (!requireNamespace("BiocManager", quietly=TRUE)) install.packages("BiocManager", repos="https://cloud.r-project.org")'
          Rscript --vanilla -e 'BiocManager::install("sparseMatrixStats", ask=FALSE, update=FALSE)'
          Rscript --vanilla -e 'remotes::install_github("davidrusi/modelSelection", dependencies = TRUE, upgrade = "never")'

      - name: Build site
        run: Rscript --vanilla -e 'bookdown::render_book("index.Rmd", output_format = "all")'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          publish_branch: gh-pages
